#=========================================================#
#                  Anti-Leak Configuration                #
#=========================================================#
 
# License/HWID Key
HWID: ""
LICENCE: ""

#=========================================================#
#                  Messages Configuration                 #
#=========================================================#

# Prefix
PREFIX: "&8[&9&lKnight]"

